language: bash
sudo: required
dist: trusty

before_install:
  - sudo apt-get update -q
  - sudo apt-get install cabal-install -y
  - cabal update
  - cabal install shellcheck-0.4.3
script:
  - ~/.cabal/bin/shellcheck *.sh
